// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Store.Infrastructure.Persistence;

#nullable disable

namespace Store.Infrastructure.Persistence.Migrations;

[DbContext(typeof(EditionDbContext))]
[Migration("20260901130000_profile-completion")]
partial class profile_completion
{
}
