// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Store.Infrastructure.Persistence;

#nullable disable

namespace Store.Infrastructure.Persistence.Migrations;

[DbContext(typeof(EditionDbContext))]
[Migration("20260901170100_add-newsletter-subscriber-table")]
partial class add_newsletter_subscriber_table
{
}
