// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Store.Infrastructure.Persistence;

#nullable disable

namespace Store.Infrastructure.Persistence.Migrations;

[DbContext(typeof(EditionDbContext))]
[Migration("20260901150000_marketing-promos")]
partial class marketing_promos
{
}
