using Store.Common.Security;

namespace Edition.Application.Models.Constants;

public static class SecurityKeyConstant
{
    public static string Tag => SecurityKeyRegistry.Get(nameof(Tag));
    public static string User => SecurityKeyRegistry.Get(nameof(User));
    public static string City => SecurityKeyRegistry.Get(nameof(City));
    public static string Bank => SecurityKeyRegistry.Get(nameof(Bank));
    public static string Role => SecurityKeyRegistry.Get(nameof(Role));
    public static string Order => SecurityKeyRegistry.Get(nameof(Order));
    public static string Wallet => SecurityKeyRegistry.Get(nameof(Wallet));
    public static string WalletTransaction => SecurityKeyRegistry.Get(nameof(WalletTransaction));
    public static string Product => SecurityKeyRegistry.Get(nameof(Product));
    public static string Province => SecurityKeyRegistry.Get(nameof(Province));
    public static string Currency => SecurityKeyRegistry.Get(nameof(Currency));
    public static string Category => SecurityKeyRegistry.Get(nameof(Category));
    public static string PostType => SecurityKeyRegistry.Get(nameof(PostType));
    public static string Property => SecurityKeyRegistry.Get(nameof(Property));
    public static string BlogPost => SecurityKeyRegistry.Get(nameof(BlogPost));
    public static string OrderItem => SecurityKeyRegistry.Get(nameof(OrderItem));
    public static string Permission => SecurityKeyRegistry.Get(nameof(Permission));
    public static string BlogPostTag => SecurityKeyRegistry.Get(nameof(BlogPostTag));
    public static string BankAccount => SecurityKeyRegistry.Get(nameof(BankAccount));
    public static string BankTransaction => SecurityKeyRegistry.Get(nameof(BankTransaction));
    public static string UserAddress => SecurityKeyRegistry.Get(nameof(UserAddress));
    public static string ProductFile => SecurityKeyRegistry.Get(nameof(ProductFile));
    public static string BlogPostFile => SecurityKeyRegistry.Get(nameof(BlogPostFile));
    public static string SubCategory => SecurityKeyRegistry.Get(nameof(SubCategory));
    public static string BlogPostLike => SecurityKeyRegistry.Get(nameof(BlogPostLike));
    public static string CommentTopic => SecurityKeyRegistry.Get(nameof(CommentTopic));
    public static string DeliveryType => SecurityKeyRegistry.Get(nameof(DeliveryType));
    public static string PropertyItem => SecurityKeyRegistry.Get(nameof(PropertyItem));
    public static string FinancialYear => SecurityKeyRegistry.Get(nameof(FinancialYear));
    public static string DeliveryOption => SecurityKeyRegistry.Get(nameof(DeliveryOption));
    public static string ProductComment => SecurityKeyRegistry.Get(nameof(ProductComment));
    public static string ProductQuestion => SecurityKeyRegistry.Get(nameof(ProductQuestion));
    public static string BlogPostComment => SecurityKeyRegistry.Get(nameof(BlogPostComment));
    public static string ChartOfAccount => SecurityKeyRegistry.Get(nameof(ChartOfAccount));
    public static string ProductProperty => SecurityKeyRegistry.Get(nameof(ProductProperty));
    public static string OrdreStatusType => SecurityKeyRegistry.Get(nameof(OrdreStatusType));
    public static string ProductCategory => SecurityKeyRegistry.Get(nameof(ProductCategory));
    public static string PropertyCategory => SecurityKeyRegistry.Get(nameof(PropertyCategory));
    public static string BlogPostCategory => SecurityKeyRegistry.Get(nameof(BlogPostCategory));
    public static string ProductDescription => SecurityKeyRegistry.Get(nameof(ProductDescription));
    public static string OrderItemAttachment => SecurityKeyRegistry.Get(nameof(OrderItemAttachment));
    public static string RolePermission => SecurityKeyRegistry.Get(nameof(RolePermission));
    public static string UserRole => SecurityKeyRegistry.Get(nameof(UserRole));
    public static string UserSession => SecurityKeyRegistry.Get(nameof(UserSession));
    public static string Page => SecurityKeyRegistry.Get(nameof(Page));
    public static string Section => SecurityKeyRegistry.Get(nameof(Section));
    public static string SectionType => SecurityKeyRegistry.Get(nameof(SectionType));
    public static string SectionItem => SecurityKeyRegistry.Get(nameof(SectionItem));
    public static string PageSection => SecurityKeyRegistry.Get(nameof(PageSection));
    public static string WebSiteSetting => SecurityKeyRegistry.Get(nameof(WebSiteSetting));
    public static string Discount => SecurityKeyRegistry.Get(nameof(Discount));
    public static string ProductFeatureType => SecurityKeyRegistry.Get(nameof(ProductFeatureType));
    public static string ProductOrderItemAttachmentType => SecurityKeyRegistry.Get(nameof(ProductOrderItemAttachmentType));
    public static string UserStory => SecurityKeyRegistry.Get(nameof(UserStory));
    public static string UserStoryComment => SecurityKeyRegistry.Get(nameof(UserStoryComment));
    public static string UserStoryLike => SecurityKeyRegistry.Get(nameof(UserStoryLike));
    public static string AssistantFaq => SecurityKeyRegistry.Get(nameof(AssistantFaq));
    public static string MarketingPromo => SecurityKeyRegistry.Get(nameof(MarketingPromo));
    public static string RoomType => SecurityKeyRegistry.Get(nameof(RoomType));
}
